Benchmark Protobuf-ES
ipfs/protons pull request #89
Opened 2023-02-10 20:44 UTC by felicio

Repo: https://github.com/bufbuild/protobuf-es
Release: https://buf.build/blog/protobuf-es-the-protocol-buffers-typescript-javascript-runtime-we-all-deserve

2023-02-10 21:10 UTC, felicio commented on packages/protons-benchmark/README.md
> +$ npm run build
⚠️ Without this:

```
$ npm start                     

> protons-benchmark@0.0.0 prestart
> npm run build


> protons-benchmark@0.0.0 build
> aegir build --no-bundle && cp -R src/protobufjs dist/src/protobufjs

[22:08:47] tsc [started]
src/protons/bench.ts:6:68 - error TS2307: Cannot find module 'protons-runtime' or its corresponding type declarations.

6 import { encodeMessage, decodeMessage, message, enumeration } from 'protons-runtime'

...

Found 89 errors in 2 files.

Errors  Files
    32  src/protons/bench.ts:6
    57  src/protons/rpc.ts:6
[22:08:48] tsc [failed]
[22:08:48] → Command failed with exit code 1: tsc

...
```

2023-02-10 21:23 UTC, felicio commented on packages/protons-benchmark/README.md
> +protobuf-es x 15,673 ops/sec ±0.48% (93 runs sampled)
ℹ️ Slowest.

2023-02-10 21:23 UTC, felicio commented on packages/protons-benchmark/README.md
> +protobuf-es x 16,032 ops/sec ±0.38% (68 runs sampled)
ℹ️ Slowest.

2023-10-13 06:06 UTC, achingbrain requested changes
Thanks for opening this & sorry it's taken me so long to get to this PR!

LGTM - just a question mark over the two yaml files that have been added - what are they for?

2023-10-13 06:11 UTC, achingbrain commented on packages/protons-benchmark/buf.gen.yaml
> +version: v1
Is there a way for this config file to live in the `protobuf-es` folder?  It'd be more manageable not to have implementation-specific files outside of their respective directories.

2023-10-13 06:12 UTC, achingbrain commented on packages/protons-benchmark/src/buf.yaml
> +version: v1
Same comment as https://github.com/ipfs/protons/pull/89/files#r1357807337

2023-10-23 12:52 UTC, merged